DROP DATABASE IF EXISTS logitech_express;
CREATE DATABASE logitech_express CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE logitech_express;

CREATE TABLE motoristas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  cpf CHAR(11) NOT NULL UNIQUE,
  cnh VARCHAR(20) NOT NULL UNIQUE,
  telefone VARCHAR(20),
  email VARCHAR(150) UNIQUE,
  status ENUM('ATIVO','INATIVO','AFASTADO') NOT NULL DEFAULT 'ATIVO',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE veiculos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  placa VARCHAR(8) NOT NULL UNIQUE,
  modelo VARCHAR(100) NOT NULL,
  tipo VARCHAR(60) NOT NULL,
  capacidade_kg DECIMAL(10,2) NOT NULL,
  status ENUM('DISPONIVEL','EM_ROTA','MANUTENCAO','INATIVO') NOT NULL DEFAULT 'DISPONIVEL',
  motorista_id INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_veiculo_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE rotas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  origem VARCHAR(150) NOT NULL,
  destino VARCHAR(150) NOT NULL,
  distancia_km DECIMAL(10,2) NOT NULL DEFAULT 0,
  data_inicio_prevista DATETIME NULL,
  data_fim_prevista DATETIME NULL,
  status ENUM('PLANEJADA','EM_EXECUCAO','CONCLUIDA','CANCELADA') NOT NULL DEFAULT 'PLANEJADA',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE coletas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  rota_id INT UNSIGNED NOT NULL,
  motorista_id INT UNSIGNED NOT NULL,
  endereco_origem VARCHAR(200) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  data_agendada DATETIME NOT NULL,
  status ENUM('AGENDADA','COLETADA','CANCELADA') NOT NULL DEFAULT 'AGENDADA',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_coleta_rota FOREIGN KEY (rota_id) REFERENCES rotas(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_coleta_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE entregas (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo_rastreio VARCHAR(40) NOT NULL UNIQUE,
  rota_id INT UNSIGNED NOT NULL,
  motorista_id INT UNSIGNED NOT NULL,
  veiculo_id INT UNSIGNED NOT NULL,
  destinatario_nome VARCHAR(120) NOT NULL,
  endereco VARCHAR(200) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  peso_kg DECIMAL(10,2) NOT NULL,
  status ENUM('PENDENTE','EM_TRANSITO','ENTREGUE','CANCELADA') NOT NULL DEFAULT 'PENDENTE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_entrega_rota FOREIGN KEY (rota_id) REFERENCES rotas(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_entrega_motorista FOREIGN KEY (motorista_id) REFERENCES motoristas(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_entrega_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE itens (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL UNIQUE,
  categoria VARCHAR(80) NOT NULL,
  unidade_medida VARCHAR(20) NOT NULL DEFAULT 'UN',
  estoque_minimo DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE estoque (
  item_id INT UNSIGNED PRIMARY KEY,
  quantidade DECIMAL(10,2) NOT NULL DEFAULT 0,
  atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_estoque_item FOREIGN KEY (item_id) REFERENCES itens(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE veiculo_itens (
  veiculo_id INT UNSIGNED NOT NULL,
  item_id INT UNSIGNED NOT NULL,
  quantidade DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (veiculo_id, item_id),
  CONSTRAINT fk_vi_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT fk_vi_item FOREIGN KEY (item_id) REFERENCES itens(id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE INDEX idx_entregas_status ON entregas(status);
CREATE INDEX idx_entregas_rota ON entregas(rota_id);
CREATE INDEX idx_coletas_data ON coletas(data_agendada);

INSERT INTO motoristas (nome, cpf, cnh, telefone, email) VALUES
('João da Silva', '11111111111', 'BR123456789', '49999990000', 'joao@logitech.local'),
('Maria Oliveira', '22222222222', 'BR987654321', '49999991111', 'maria@logitech.local');

INSERT INTO veiculos (placa, modelo, tipo, capacidade_kg, motorista_id) VALUES
('ABC1D23', 'Daily 35-160', 'VAN', 3500, 1),
('XYZ9K87', 'FH 460', 'CAMINHAO', 12000, 2);

INSERT INTO rotas (codigo, origem, destino, distancia_km, status) VALUES
('R-001', 'Joaçaba - SC', 'Chapecó - SC', 145.50, 'PLANEJADA'),
('R-002', 'Joaçaba - SC', 'Lages - SC', 190.00, 'PLANEJADA');

INSERT INTO itens (nome, categoria, unidade_medida, estoque_minimo) VALUES
('Pneu reserva', 'Segurança', 'UN', 2),
('Kit primeiros socorros', 'Segurança', 'UN', 2),
('Cinta de amarração', 'Carga', 'UN', 10);

INSERT INTO estoque (item_id, quantidade) VALUES (1, 8), (2, 5), (3, 30);
